name: Host On Heroku

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 

        with:

          region: "us"

          branch: "master"

          usedocker: true

          stack: "container"

          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

          docker_heroku_process_type: worker
        env:
          HD_CONFIG_FILE_URL: ${{secrets.CONFIG_FILE_URL}}
